# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: IntelliJ HTTP Client with GitHub Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Download ijhttp
      run: curl -f -s -L -o ijhttp.zip https://jb.gg/ijhttp/latest
    - name: Unpack ijhttp
      run: unzip -nq ijhttp.zip -d target
    - name: Remove ijhttp.zip
      run: rm ijhttp.zip
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: ./mvnw verify -ntp -Pspring-boot,maven-plugin
    - name: Temporarily save test requests
      uses: actions/upload-artifact@master
      with:
        name: tests
        path: funds.http
        retention-days: 1
    - name: Temporarily save target
      uses: actions/upload-artifact@master
      with:
        name: target
        path: target
        retention-days: 1

  integration-test:

    runs-on: ubuntu-latest
    needs: build
    container:
      image: jetbrains/intellij-http-client:latest

    steps:
      - name: Retrieve saved test requests
        uses: actions/download-artifact@master
        with:
          name: tests
          path: .
      - name: Retrieve saved target
        uses: actions/download-artifact@master
        with:
          name: target
          path: target
      - name: Run the application
        run: java -jar target/ijhttp-demo-1.0.0-SNAPSHOT.jar &
      - name: Wait the application
        run: while ! nc -z localhost 8080 </dev/null; do sleep 5; done
      - name: Run tests
        run: java -cp "/intellij-http-client/*" com.intellij.httpClient.cli.HttpClientMain --report funds.http
